---
abstract: 'integrated argument and option processing for Perl'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::More: 0
  Test::Output: 0
  utf8::all: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OptArgs
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Encode: 0
  Exporter::Tidy: 0
  Getopt::Long: 2.37
  I18N::Langinfo: 0
  Scalar::Util: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/mlawren/optargs
version: 0.0.1_17
